Use rasp and fix data handler
anidata/palantiri pull request #11
Opened 2017-09-03 05:38 UTC by dlrobertson

- Use rasp for http goodness
 - Punt the old data handler
   - Create a data handler thread that bulk inserts at some interval
   - The worker threads now just post their retrieved pages to this
     list of pages to be bulk inserted with `executemany`
   - Rely on `psycopg2`s encoding. Don't try to hand format the
     insert string.
   - Remove MongoDB stuff
   - Remove wierd exceptions
 - Remove old codez
 - Re-License to a more liberal license (BSD)

This is far from complete, but this removes a lot of old stuff that
either doesn't work or is super fragile. After this 60% of the time it
*should* work all of the time.

2017-09-03 05:40 UTC, dlrobertson commented
Thanks @baronvonbadguy and @wdm0006 for making this possible.

2017-09-03 15:33 UTC, bmenn requested changes
I think we should add `anidata/rasp` to `setup.py`, but otherwise lgtm.

2017-09-03 15:33 UTC, bmenn commented on example.py
> +# Copyright (c) 2017 Anidata
Not important right now, but I think we need to pick a license and stick to it and centralize in the near future.

2017-09-06 23:23 UTC, bmenn approved these changes

2017-09-06 23:23 UTC, bmenn commented
Made the change requested here in #12.

2017-09-06 23:24 UTC, merged